import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export const generateBillPDF = (shopData, billData, cartItems) => {
  const doc = new jsPDF()

  // Header gradient bar
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, 210, 35, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(shopData.shopName, 14, 18)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`GST: ${shopData.gstNumber}  |  Ph: ${shopData.phone}`, 14, 27)

  // Bill Info
  doc.setTextColor(30, 30, 60)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('INVOICE', 155, 15)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Bill No: #${billData.billNumber}`, 155, 22)
  doc.text(`Date: ${new Date(billData.createdAt).toLocaleDateString('en-IN')}`, 155, 28)

  // Customer Info
  doc.setFillColor(245, 247, 255)
  doc.rect(10, 40, 190, 20, 'F')
  doc.setFontSize(10)
  doc.setTextColor(70, 70, 100)
  doc.text(`Customer: ${billData.customerName}`, 14, 50)
  doc.text(`Phone: ${billData.customerPhone}`, 100, 50)
  doc.text(`Payment: ${billData.paymentMode}`, 14, 57)

  // Items Table
  autoTable(doc, {
    startY: 65,
    head: [['#', 'Item', 'Qty', 'Price', 'GST%', 'Amount']],
    body: cartItems.map((item, i) => {
      const gst = (item.sellingPrice * item.qty * item.gstPercent) / 100
      const amount = item.sellingPrice * item.qty + gst
      return [
        i + 1,
        item.name,
        item.qty,
        `₹${item.sellingPrice.toFixed(2)}`,
        `${item.gstPercent}%`,
        `₹${amount.toFixed(2)}`
      ]
    }),
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [99, 102, 241], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 249, 255] },
    theme: 'striped'
  })

  const finalY = doc.lastAutoTable.finalY + 10

  // Summary Box
  doc.setFillColor(245, 247, 255)
  doc.rect(120, finalY, 80, 40, 'F')
  doc.setFontSize(9)
  doc.setTextColor(80, 80, 120)
  doc.text(`Subtotal:`, 125, finalY + 10)
  doc.text(`₹${billData.subtotal.toFixed(2)}`, 195, finalY + 10, { align: 'right' })
  doc.text(`GST Amount:`, 125, finalY + 20)
  doc.text(`₹${billData.gstAmount.toFixed(2)}`, 195, finalY + 20, { align: 'right' })
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(99, 102, 241)
  doc.text(`TOTAL:`, 125, finalY + 32)
  doc.text(`₹${billData.totalAmount.toFixed(2)}`, 195, finalY + 32, { align: 'right' })

  // Footer
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(150, 150, 180)
  doc.text('Thank you for your business! — Generated by SellNiti', 105, 285, { align: 'center' })

  doc.save(`Bill-${billData.billNumber}-${billData.customerName}.pdf`)
}